#!/usr/bin/perl

#  Copyright (C) 2011 DeNA Co.,Ltd.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#  Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

## Note: This is a sample script and is not complete. Modify the script based on your environment.

use strict;
use warnings FATAL => 'all';

use Getopt::Long;

#new_master_host and new_slave_hosts are set only when recovering master succeeded
my ( $dead_master_host, $new_master_host, $new_slave_hosts, $subject, $body );
GetOptions(
  'orig_master_host=s' => \$dead_master_host,
  'new_master_host=s'  => \$new_master_host,
  'new_slave_hosts=s'  => \$new_slave_hosts,
  'subject=s'          => \$subject,
  'body=s'             => \$body,
);

# Do whatever you want here

if ($new_master_host){
`sh /etc/masterha/app1/scripts/alert.sh "统计平台 config mysql 主从切换" "$dead_master_host is dead. $new_master_host is the new master.success."`;
}else{
`sh /etc/masterha/app1/scripts/alert.sh "统计平台 config mysql 主从切换" "$dead_master_host is dead.but failover failed.check the log"`;
&recover_after_failover_failed();
}

sub recover_after_failover_failed(){
my $vip = '192.168.56.200';
my $key =2;
my $start_interface="eth0";
my $stop_interface="eth0";
my $ssh_user="root";
my $ssh_start_vip = "/sbin/ifconfig $start_interface:$key $vip/24;arping -A -c 1 $vip";
`ping -W 1 -c 1  $dead_master_host  && ssh  $ssh_user\@$dead_master_host \" $ssh_start_vip \"`;
}

exit 0;
